name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t \
          asia-south1-docker.pkg.dev/gen-lang-client-0473959611/answer-app/app:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push \
          asia-south1-docker.pkg.dev/gen-lang-client-0473959611/answer-app/app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-vision-api \
          --image=asia-south1-docker.pkg.dev/gen-lang-client-0473959611/answer-app/app:${{ github.sha }} \
          --region=asia-south1 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars=ENV=prod
